export enum AISource {
  GEMINI = 'Gemini',
  CHATGPT = 'ChatGPT',
  CLAUDE = 'Claude',
  MANUS = 'Manus',
  OTHER = 'Other'
}

export interface StockAsset {
  id: string;
  ticker: string;
  companyName: string;
  quantity: number;
  avgPrice: number;
  currentPrice: number; // Mocked for this demo or updated via AI
  source: AISource;
  iconUrl?: string; // Generated by Nano Banana
  lastUpdated: number;
}

export interface PortfolioSummary {
  totalValue: number;
  totalCost: number;
  totalGain: number;
  gainPercentage: number;
}

export interface NewsItem {
  headline: string;
  summary: string;
  url?: string;
  source?: string;
}

export interface ChatMessage {
  role: 'user' | 'model';
  text: string;
  isThinking?: boolean;
}

export interface PortfolioHistoryItem {
  date: string;
  value: number;
}